version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: rohan
      WORDPRESS_DB_PASSWORD: rohan
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: rohan
      MYSQL_PASSWORD: rohan
      MYSQL_RANDOM_ROOT_PASSWORD: rohan
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
